// <auto-generated />
using System;

using DotnetVibe.ApiService.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetVibe.ApiService.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("AddProcessedTemperatureMessages")]
partial class AddProcessedTemperatureMessages
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DotnetVibe.ApiService.Data.ProcessedTemperatureMessage", b =>
            {
                b.Property<string>("MessageId")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<DateTimeOffset>("ProcessedAt")
                    .HasColumnType("datetimeoffset");

                b.HasKey("MessageId");

                b.ToTable("ProcessedTemperatureMessages");
            });

        modelBuilder.Entity("DotnetVibe.ApiService.Data.WeatherForecast", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<int>("TemperatureC")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("Date")
                    .IsUnique();

                b.ToTable("WeatherForecasts");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Date = new DateOnly(2026, 6, 10),
                        TemperatureC = 22
                    },
                    new
                    {
                        Id = 2,
                        Date = new DateOnly(2026, 6, 11),
                        TemperatureC = 18
                    },
                    new
                    {
                        Id = 3,
                        Date = new DateOnly(2026, 6, 12),
                        TemperatureC = 25
                    },
                    new
                    {
                        Id = 4,
                        Date = new DateOnly(2026, 6, 13),
                        TemperatureC = 12
                    },
                    new
                    {
                        Id = 5,
                        Date = new DateOnly(2026, 6, 14),
                        TemperatureC = 30
                    });
            });

        modelBuilder.Entity("DotnetVibe.ApiService.WeatherMap.Data.PinnedLocation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<double>("Latitude")
                    .HasColumnType("float");

                b.Property<double>("Longitude")
                    .HasColumnType("float");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("SortOrder")
                    .HasColumnType("int");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.HasKey("Id");

                b.HasIndex("UserId", "SortOrder");

                b.ToTable("PinnedLocations");
            });
#pragma warning restore 612, 618
    }
}
