// <auto-generated />
using System;
using DotnetVibe.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetVibe.ApiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        // If you encounter a merge conflict in the line below, it means you need to
        // discard one of the migration branches and recreate its migrations on top of
        // the other branch. See https://aka.ms/efcore-docs-migrations-conflicts for more info.
        public override string LastMigrationId => "20260624132511_RemoveSummaryFromWeatherForecast";

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "11.0.0-preview.5.26302.115")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotnetVibe.ApiService.Data.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2026, 6, 10),
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2026, 6, 11),
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2026, 6, 12),
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2026, 6, 13),
                            TemperatureC = 12
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2026, 6, 14),
                            TemperatureC = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
